test_job:
  stage: test
  image: python:3.7
  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - echo "Running tests"
    - pytest tests/

documentation:
  stage: deploy
  script:
    - mkdir public
    - cp documentation/Main.pdf public
  artifacts:
    paths:
      - public
