test_job:
  stage: test
  image: python:3.7
  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - echo "Running tests"
    - pytest tests/


compile_pdf:
  stage: build
  image: timnn/texlive
  script:
    - cd documentation
    - pdflatex Main.tex

pages:
  stage: deploy
  script:
    - cp documentation/Main.pdf .
  artifacts:
    paths:
      - .