test_job:
  stage: test
  image: python:3.7
  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - echo "Running tests"
    - pytest tests/


compile_pdf:
  stage: build
  image: latex-minted
  script:
    - cd documentation
    - pdflatex --shell-escape Main.tex

documentation:
  stage: deploy
  script:
    - mkdir public
    - cp documentation/Main.pdf public
  artifacts:
    paths:
      - public
